# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74932478863c8c286eac5288828bf5cb1839656bae1a90394b29e9b186aa6632dc786c00d25463775986a8fe4f61737d8470b2123cff249de8ca482bf5564886

test:
  secret_key_base: f896ace789e93fa518f223798c4ee5fd6fee88a239c4660de679e1e733f25861da7ca9f9e7f2e539d23fbb39faec324eb34a13d5ee34d8ff1fda291203015330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
